Question 1

In [5]:
import pandas as pd

data = pd.DataFrame({
    "Tid": range(1, 11),
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital_Status": ["Single", "Married", "Single", "Married", "Divorced",
                       "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable_Income": [125, 100, 70, 120, 95, 60, 220, 85, 75, 90],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
})

data

   Tid Refund Marital_Status  Taxable_Income Cheat
0    1    Yes         Single             125    No
1    2     No        Married             100    No
2    3     No         Single              70    No
3    4    Yes        Married             120    No
4    5     No       Divorced              95   Yes
5    6     No        Married              60    No
6    7    Yes       Divorced             220    No
7    8     No         Single              85   Yes
8    9     No        Married              75    No
9   10     No         Single              90   Yes

Question 2

In [6]:
data.iloc[[0, 4, 7, 8]]

   Tid Refund Marital_Status  Taxable_Income Cheat
0    1    Yes         Single             125    No
4    5     No       Divorced              95   Yes
7    8     No         Single              85   Yes
8    9     No        Married              75    No

Question 3)1.

In [7]:
data.iloc[3:8]

   Tid Refund Marital_Status  Taxable_Income Cheat
3    4    Yes        Married             120    No
4    5     No       Divorced              95   Yes
5    6     No        Married              60    No
6    7    Yes       Divorced             220    No
7    8     No         Single              85   Yes

Question 3)2.

In [8]:
data.iloc[4:9, 2:5]

  Marital_Status  Taxable_Income Cheat
4       Divorced              95   Yes
5        Married              60    No
6       Divorced             220    No
7         Single              85   Yes
8        Married              75    No

Question 3)3.

In [9]:
data.iloc[:, 1:4]

  Refund Marital_Status  Taxable_Income
0    Yes         Single             125
1     No        Married             100
2     No         Single              70
3    Yes        Married             120
4     No       Divorced              95
5     No        Married              60
6    Yes       Divorced             220
7     No         Single              85
8     No        Married              75
9     No         Single              90

Question-4

In [11]:
df=pd.read_csv("Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Question 5

In [12]:
df = df.drop(index=4).drop(df.columns[3], axis=1)
df

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

Question 6)

In [13]:
import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 80000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-05-01",
                     "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

df = pd.DataFrame(data)

df.to_csv("employees.csv", index=False)

df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,80000,12,2010-11-25,Male,5000,3.5

In [14]:
df = pd.read_csv("employees.csv")
df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,80000,12,2010-11-25,Male,5000,3.5

In [15]:
df.shape

(5, 10)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

In [17]:
df.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.000000,5.000000,5.0,5.000000
mean,103.000000,34.000000,64000.000000,7.400000,5500.0,4.100000
std,1.581139,5.612486,11937.336386,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.000000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.000000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,65000.000000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,70000.000000,10.000000,6000.0,4.500000
max,105.000000,41.000000,80000.000000,12.000000,7000.0,4.700000

In [18]:
df.head(5)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,80000,12,2010-11-25,Male,5000,3.5

In [19]:
df.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,80000,12,2010-11-25,Male,5000,3.5

In [20]:
df["Salary"].mean()

np.float64(64000.0)

In [21]:
df["Bonus"].sum()

np.int64(27500)

In [22]:
df.loc[df["Age"].idxmin()]

Employee_ID                   104
Name                        Diana
Department              Marketing
Age                            28
Salary                      55000
Years_of_Experience             3
Joining_Date           2021-02-10
Gender                     Female
Bonus                        4500
Rating                        4.7
Name: 3, dtype: object

In [23]:
df["Rating"].max()

4.7

In [24]:
df = df.sort_values(by="Salary", ascending=False)
df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
4,105,Edward,Sales,38,80000,12,2010-11-25,Male,5000,3.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

In [25]:
def performance(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

df["Performance"] = df["Rating"].apply(performance)

df

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
4,105,Edward,Sales,38,80000,12,2010-11-25,Male,5000,3.5,Average
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent

In [26]:
df.isnull().sum()

Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Performance            0
dtype: int64

In [27]:
df.rename(columns={"Employee_ID": "ID"}, inplace=True)

df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
4,105,Edward,Sales,38,80000,12,2010-11-25,Male,5000,3.5,Average
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent

In [28]:
df[df["Years_of_Experience"] > 5]

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
4,105,Edward,Sales,38,80000,12,2010-11-25,Male,5000,3.5,Average
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6000,3.8,Average

In [29]:
df[df["Department"] == "IT"]

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6000,3.8,Average

In [30]:
df["Tax"] = df["Salary"] * 0.10

df

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance,Tax
4,105,Edward,Sales,38,80000,12,2010-11-25,Male,5000,3.5,Average,8000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-05-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0

In [31]:
df.to_csv("employees_modified.csv", index=False)